//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Headset
    {
        public int ID_PRODUCT { get; set; }
        public string NAME { get; set; }
        public string CHARACTERISTICS { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string URL { get; set; }
    }
}
