//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PcShopEntities : DbContext
    {
        private static PcShopEntities _context;
        public PcShopEntities()
            : base("name=PcShopEntities")
        {
        }
        public static PcShopEntities GetContext()
        {
            if (_context == null)
                _context = new PcShopEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Headset> Headset { get; set; }
        public virtual DbSet<Keyboard> Keyboard { get; set; }
        public virtual DbSet<Mouse> Mouse { get; set; }
        public virtual DbSet<Сomputer> Сomputer { get; set; }
    }
}
